import type { Metadata } from "next";
import "./globals.css";
import { Header } from "@/components/Header";
import { Breadcrumb } from "@/components/Breadcrumb"
import { VercelToolbar } from '@vercel/toolbar/next';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const shouldInjectToolbar = process.env.NODE_ENV === 'development';
  return (
    <html lang="en">
      <body>
        <Header />
        <Breadcrumb />
        {children}
        {shouldInjectToolbar && <VercelToolbar />}
      </body>
    </html>
  );
}
