import type { Metadata } from "next";
import "./globals.css";
import { Header } from "@/components/Header";
import { Breadcrumb } from "@/components/Breadcrumb"


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        <Breadcrumb />
        {children}
      </body>
    </html>
  );
}
